apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: fio-cronjob
  namespace: ceph-canary 
spec:
  schedule: "*/10 * * * *"
  successfulJobsHistoryLimit: 0 
  failedJobsHistoryLimit: 0
  concurrencyPolicy: Forbid
  jobTemplate:
    metadata:
      labels:
        cronjob:  fio-cronjob
    spec:
      template:
        metadata:
          labels:
            cronjob:  fio-cronjob
        spec:
          serviceAccountName: ceph-canary
          containers:
          - name: ose-cli
            image: OSECLI_IMAGE_REPO 
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            args:
            - '-c'
            - '/fio/bin/fio_canary.sh'
            volumeMounts: 
            - name: fio-canary-volume 
              mountPath: /fio/bin 
            - name: config-fioloadpvc-volume 
              mountPath: /fio/config-fioloadpvc
            - name: config-fiopod-volume 
              mountPath: /fio/config-fiopod
          volumes:
          - name: fio-canary-volume
            configMap:
              name: fio-canary
              defaultMode: 0755
          - name: config-fioloadpvc-volume
            configMap:
              name: fio-load-pvc
          - name: config-fiopod-volume
            configMap:
              name: fio-pod
          restartPolicy: OnFailure
